### PR TITLE
Only start bulk inserting when we have a stream

### LINKED ISSUE #27: Tests fails on Mac 50% of the time
I'm not sure why, but the first test of `abstractTests.js` fails.

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #27

### CODE REVIEW

**Comment by mcollina** [comment]
What do you think @robertsLando?

**Review by robertsLando — APPROVED** [review]
LGTM. I dunno why it doesn't happen on Ubuntu, maybe mongodb driver is "quicker" on ubuntu 🤷🏼‍♂️ anyway it's ok to wait the stream before starting a bulk insert.

**Comment by mcollina** [comment]
@robertsLando this should be the "proper" fix.

**Review by robertsLando — COMMENTED** [review]
Could you please try to run aedes-tests using this?

**Comment by mcollina** [comment]
Not currently unfortunately :(.

**Comment by robertsLando** [comment]
@mcollina any progress on this?

**Comment by mcollina** [comment]
I have no more time to dedicate to this for a while. Happy to land or if you'd like to test further, I can wait for that too.

**Comment by robertsLando** [comment]
@mcollina I just took a closer look to the code, seems we have finally found the right way :) I'm absolutely +1 for this to land

**Comment by robertsLando** [comment]
I have also make a quick test of this branch with aedes-tests and everything looks great! Let me know when you do a release of this :)

**Comment by mcollina** [comment]
shipped!

**Pull request merged**
