### PR TITLE
fix: Better handle of lastId to fix emitter when using with clusters

### LINKED ISSUE #17: [bug] Missing messages when running in clusters
See https://github.com/moscajs/aedes-tests/pull/5#issuecomment-616449835

### PR DESCRIPTION
**Pull request by robertsLando**
Seems that manually creating lastId using mongodb method makes the query loose some messages when using with clusters

Fixes #17

### CODE REVIEW

**Comment by robertsLando** [comment]
Finally made it work :rocket:  @mcollina

**Comment by mcollina** [comment]
Awesome! It would be good to include a test CI or something for this, I would prefer not to regress.

**Comment by robertsLando** [comment]
I think I could try by adding a doc with a manually created id, will check it tomorrow! 

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by robertsLando** [comment]
@mcollina Should be ready now! Remember to also make a patch release so I can fix aedes-test :smiley:

**Comment by robertsLando** [comment]
@mcollina ping?

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
