### PR TITLE
convert buffer to string before inserts

### PR DESCRIPTION
**Pull request by GavinDmello**
Related to #3

### CODE REVIEW

**Comment by mcollina** [comment]
I think we should convert the payload back to a Buffer if it's a BSON binary instead. Before we send it forward.

**Comment by mcollina** [comment]
What I mean is that we should convert `Buffer` to `Binary`, not strings: http://mongodb.github.io/node-mongodb-native/2.2/api/Binary.html

**Comment by GavinDmello** [comment]
oops!

**Comment by mcollina** [comment]
@GavinDmello would you mind adding a unit test?

**Comment by GavinDmello** [comment]
Sure. It will be in mqemitter right ?

**Pull request merged**
