### PR TITLE
Bro/mongo options

### PR DESCRIPTION
**Pull request by bro-jo**
#13

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Good work! Would you mind adding a unit test for this change?

**Comment by bro-jo** [comment]
Ok, I will write test code on `<project_dir>/test.js`, is it right?

**Comment by mcollina** [comment]
yes!

**Comment by bro-jo** [comment]
I've pushed some test code. Review please.

**Review by mcollina — COMMENTED** [review]
Would you mind to avoid the usage of setTimeout? It makes the test brittle.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by bro-jo** [comment]
I found some event emitter which is `status` of MQEmitterMongoDB. So, I replaced setTimeout with event listener. That will make the test more stable.

**Pull request merged**
